# Relative path to source code directory
file_source: "/OriginalFiles/HelloCode/"

# Relative path to test code directory
test_source: "/OriginalFiles/HelloCodeTests/"

# Items to exclude from mutation
# - file_path: "File Name Here"
#   entire_file: true/false
#   methods:
#     - "Method Name Here"
#   operators:
#     - "Operator Here"
exclusions:
  directories:
  files:
    - filename: "HelloWorld_UnmutatedCopy.py"
      entire_file: true
      methods:
      operators:

# The relative path where the mutation report will be generated
report_directory: "/MutationReports/"

report_filename: "output.txt"

mutations: "mutations.txt"

mutation_map: "mutationMap.txt"

# Can set default timeout overall, per file, per method, per mutant type, or none with 0/null
timeouts:
  default_timeout: 5
  files:
    - HelloWorld.py:
        default_timeout: 20
        methods:
          - makeArray: 0.0000001
          - divideMe: 0.01
        mutants:
          - IF: 0.001
          - SUBTRACT: 0